### ISSUE TITLE
libhitaki.so.0 not found

### ISSUE THREAD

**Issue by seanjean3000** [alsa-project/libhitaki#4] opened 2022-12-19 00:00 UTC
I installed libhitaki (the same way I did for libhinawa), but when I try to run snd-bebob-ctl-service I get the message "snd-bebob-ctl-service: error while loading shared libraries: libhitaki.so.0: cannot open shared object file: No such file or directory."

Running meson test -C build-directory doesn't seem to show any problems.

Not sure what I did wrong here or how to fix it. Thanks

**Comment by takaswie** [comment] 2022-12-19 01:39
Hi,

Thanks for the report, and I apologize your inconvenience.

In my opinion, the installation path of your environe:ment seems not to be the expected one. Would you check it in your build directory? Like:

```
$ cd your-local-repository-of-libhitaki
$ meson configure relative-path-to-your-build-directory
```

We can see the list of configuration for the latest installation.

Regards

**Comment by seanjean3000** [comment] 2022-12-19 02:13
Thank you for the quick reply.

I think the part from the meson configuration report that is relevant is this: (?)

Directories         Current Value        Possible Values                                               Description
  -----------         -------------        ---------------                                               -----------
  bindir              bin                                                                                Executable directory
  datadir             share                                                                              Data file directory
  includedir          include                                                                            Header file directory
  infodir             share/info                                                                         Info page directory
  libdir              lib/x86_64-linux-gnu                                                               Library directory
  libexecdir          libexec                                                                            Library executable directory
  localedir           share/locale                                                                       Locale data directory
  localstatedir       /var/local                                                                         Localstate data directory
  mandir              share/man                                                                          Manual page directory
  prefix              /usr/local                                                                         Installation prefix
  sbindir             sbin                                                                               System executable directory
  sharedstatedir      /var/local/lib                                                                     Architecture-independent data directory
  sysconfdir          etc   


*Sorry -- the spacing gets lost here so this is a bit hard to read*

**Comment by takaswie** [comment] 2022-12-19 07:49
```
bindir bin Executable directory
datadir share Data file directory
includedir include Header file directory
infodir share/info Info page directory
libdir lib/x86_64-linux-gnu Library directory
libexecdir libexec Library executable directory
localedir share/locale Locale data directory
localstatedir /var/local Localstate data directory
mandir share/man Manual page directory
prefix /usr/local Installation prefix
sbindir sbin System executable directory
sharedstatedir /var/local/lib Architecture-independent data directory
sysconfdir etc
```

Okay. It looks to be expected.

Next, let us check binary metadata about dynamic linking of `snd-bebob-ctl-service`.

```
$ cd local-repository-of-snd-firewire-ctl-services
$ ldd ./target/debug/snd-bebob-ctl-service
	linux-vdso.so.1 (0x00007ffcae368000)
	libhitaki.so.0 => /lib/x86_64-linux-gnu/libhitaki.so.0 (0x00007f912b12e000)
	libhinawa.so.2 => /lib/x86_64-linux-gnu/libhinawa.so.2 (0x00007f912b119000)
	libalsatimer.so.0 => /lib/x86_64-linux-gnu/libalsatimer.so.0 (0x00007f912b10b000)
	libalsaseq.so.0 => /lib/x86_64-linux-gnu/libalsaseq.so.0 (0x00007f912b0ec000)
	libalsactl.so.0 => /lib/x86_64-linux-gnu/libalsactl.so.0 (0x00007f912b0d9000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f912b075000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f912a4c7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f912b055000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f912a200000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f912b163000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f912b02a000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f912b01b000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f912a42c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f912a117000)
```

**Comment by seanjean3000** [comment] 2022-12-19 15:19
Yes... some problems here:

$ ldd ./target/debug/snd-bebob-ctl-service
	linux-vdso.so.1 (0x00007ffd967a3000)
	libhitaki.so.0 => not found
	libhinawa.so.2 => /lib/x86_64-linux-gnu/libhinawa.so.2 (0x00007fc40b775000)
	libalsatimer.so.0 => not found
	libalsaseq.so.0 => not found
	libalsactl.so.0 => not found
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fc40b71b000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fc40b5ea000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc40b5d0000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc40b5c6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc40b5a4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc40b59e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc40b3c9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc40c16d000)
	libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007fc40b3bb000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fc40b348000)

So it looks like alsa-gobject also is not being found, which is also odd because again I installed that the same way and meson test shows no issues there either.

**Comment by takaswie** [comment] 2022-12-20 02:43
Good. We identify that the cause is dynamic loader (=program interpreter) can find no ELF shared object for soname of the library installed by hand. Let us check search path coded in
the interpreter.

```
$ readelf -l target/debug/snd-bebob-ctl-service  | grep interpreter
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
```

When calling the interpreter with `--help` command-line argument, we could see:

```
$ /lib64/ld-linux-x86-64.so.2 --help
...
Shared library search path:
  (libraries located via /etc/ld.so.cache)
  /lib/x86_64-linux-gnu (system search path)
  /usr/lib/x86_64-linux-gnu (system search path)
  /lib (system search path)
  /usr/lib (system search path)
...
```

We can see additional configurations when searching `/etc/ld.so.conf` and files under `/etc/ld.so.conf.d`.

```
$ grep local /etc/ld.so.conf
(nothing found)
$ rgrep local /etc/ld.so.conf.d/
/etc/ld.so.conf.d/libc.conf:/usr/local/lib
/etc/ld.so.conf.d/i386-linux-gnu.conf:/usr/local/lib/i386-linux-gnu
/etc/ld.so.conf.d/i386-linux-gnu.conf:/usr/local/lib/i686-linux-gnu
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:/usr/local/lib/x86_64-linux-gnu
```

As we checked, meson configuration installs these binaries under the path of `/usr/local`.

```
$ find /usr/local | grep hitaki
(found)
```

Please compare the path of installed binary and the list of search paths. The above outputs
could be different depending on system.

> So it looks like alsa-gobject also is not being found, which is also odd because again I installed that the same way and meson test shows no issues there either.

At present, I program the test for pre-installed binaries, thus give no guarantee for installation.

**Comment by takaswie** [comment] 2022-12-20 02:44
I made a mistake to close the issue, now reopen...

**Comment by seanjean3000** [comment] 2022-12-20 14:10
Thank you again for your continued help.

1) `$ readelf -l target/debug/snd-bebob-ctl-service  | grep interpreter`

    returns `[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]`

2) `$ /lib64/ld-linux-x86-64.so.2 --help`

    returns `--help: error while loading shared libraries: --help: cannot open shared object file`
 
3) Other configurations:: 

```
$ grep local /etc/ld.so.conf
/usr/local/lib/libgoocanvas3
```
and
```
$ rgrep local /etc/ld.so.conf.d/
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:/usr/local/lib/x86_64-linux-gnu
/etc/ld.so.conf.d/libc.conf:/usr/local/lib
/etc/ld.so.conf.d/i386-linux-gnu.conf:/usr/local/lib/i386-linux-gnu
/etc/ld.so.conf.d/i386-linux-gnu.conf:/usr/local/lib/i686-linux-gnu
```

4) And checking for where meson put the files:

```
$ find /usr/local | grep hitaki
/usr/local/include/hitaki
/usr/local/include/hitaki/snd_motu_register_dsp_parameter.h
/usr/local/include/hitaki/snd_digi00x.h
/usr/local/include/hitaki/efw_protocol.h
/usr/local/include/hitaki/hitaki.h
/usr/local/include/hitaki/alsa_firewire.h
/usr/local/include/hitaki/hitaki_enums.h
/usr/local/include/hitaki/snd_tascam.h
/usr/local/include/hitaki/motu_command_dsp.h
/usr/local/include/hitaki/tascam_protocol.h
/usr/local/include/hitaki/snd_unit.h
/usr/local/include/hitaki/hitaki_sigs_marshal.h
/usr/local/include/hitaki/snd_efw.h
/usr/local/include/hitaki/hitaki_enum_types.h
/usr/local/include/hitaki/motu_register_dsp.h
/usr/local/include/hitaki/quadlet_notification.h
/usr/local/include/hitaki/snd_dice.h
/usr/local/include/hitaki/snd_motu.h
/usr/local/lib/x86_64-linux-gnu/pkgconfig/hitaki.pc
/usr/local/lib/x86_64-linux-gnu/libhitaki.so.0.1.1
/usr/local/lib/x86_64-linux-gnu/libhitaki.so
/usr/local/lib/x86_64-linux-gnu/libhitaki.so.0
```

**Comment by takaswie** [comment] 2022-12-21 00:17
Thanks. As a quick glance, the issue belongs to the domain of Linux distribution design. For my information, would I ask you what kind of Linux distribution and what version of it you use?

**Comment by seanjean3000** [comment] 2022-12-21 02:08
Your question about the distribution lead me to the answer, and I have to apologize, this was a very dumb mistake on my part. I am using MXLinux, which comes with but does not use systemd by default. I thought I had enabled systemd as default but I hadn't; now that I've fixed that I am able to run this service. (Yet to try with my Lightbridge.)

Again, many apologies. Thank you for your assistance.

**Closed as completed** 2022-12-21 02:08 UTC
Labels: question

**Comment by takaswie** [comment] 2022-12-21 04:25
> I've fixed that I am able to run this service.

Good to hear it.

> (Yet to try with my Lightbridge.)

It's one of my test devices and ALSA bebob driver often fail to drive the device for stable packet sequences. You could see many kernel logs reporting packet discontinuities.

 * https://github.com/takaswie/snd-firewire-improve/issues/37

But sometimes we get stable packet sequences. I have no idea to fix it yet...

**Comment by rusk911** [comment] 2025-05-05 14:56
Same here on Ubuntustudio 24.04
Package was compiled, installed, but failing to run.
```
$ /home/dima/.cargo/bin/snd-dice-ctl-service
/home/dima/.cargo/bin/snd-dice-ctl-service: error while loading shared libraries: libalsaseq.so.0: cannot open shared object file: No such file or directory
```
Tried above investigations with similar results except last step, wich found nothing in /usr/local.
libhitaki and sources was installed with apt.
```
$ ldd ./target/debug/snd-dice-ctl-service
        linux-vdso.so.1 (0x00007fff15da3000)
        libalsatimer.so.0 => not found
        libalsaseq.so.0 => not found
        libhitaki.so.0 => /lib/x86_64-linux-gnu/libhitaki.so.0 (0x00007d2e626a9000)
        libhinawa.so.4 => /lib/x86_64-linux-gnu/libhinawa.so.4 (0x00007d2e6269b000)
        libalsactl.so.0 => not found
        libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007d2e61230000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007d2e62636000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007d2e610e7000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007d2e62608000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007d2e60e00000)
        /lib64/ld-linux-x86-64.so.2 (0x00007d2e626e6000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007d2e625ff000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007d2e625e3000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007d2e6109a000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007d2e6106d000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007d2e61061000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007d2e60d17000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007d2e60c7d000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007d2e61024000)

```

**Comment by takaswie** [comment] 2025-05-06 09:48
Hi @rusk911,

> $ /home/dima/.cargo/bin/snd-dice-ctl-service
> /home/dima/.cargo/bin/snd-dice-ctl-service: error while loading shared libraries: libalsaseq.so.0: cannot open shared object file: No such file or directory

It's one of libraries provided by [alsa-gobject](https://github.com/alsa-project/alsa-gobject/) project.

**Comment by rusk911** [comment] 2025-05-06 17:12
Thank you. I have installed it with sudo, then copied symlinks to /usr/lib. It works now.
